<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="hoangcv" name="Default test" tests="6" failures="1" timestamp="15 Nov 2019 03:24:56 GMT" time="35.386" errors="0">
  <testcase name="TC_1" time="1.647" classname="autotest.NewTest3"/>
  <testcase name="TC_2" time="0.209" classname="autotest.NewTest3"/>
  <testcase name="TC_3" time="0.281" classname="autotest.NewTest3"/>
  <testcase name="TC_4" time="1.765" classname="autotest.NewTest3"/>
  <testcase name="TC_5" time="2.748" classname="autotest.NewTest3">
    <failure type="org.junit.ComparisonFailure" message="expected:&amp;lt;Chu Hoàng[]&amp;gt; but was:&amp;lt;Chu Hoàng[
hoangcv@vnpay.vn
Change Password]&amp;gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<Chu Hoàng[]> but was:<Chu Hoàng[
hoangcv@vnpay.vn
Change Password]>
	at org.junit.Assert.assertEquals(Assert.java:125)
	at org.junit.Assert.assertEquals(Assert.java:147)
	at autotest.NewTest3.TC_5(NewTest3.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
    </failure>
  </testcase> <!-- TC_5 -->
  <testcase name="TC_6" time="10.002" classname="autotest.NewTest3"/>
</testsuite> <!-- Default test -->
